    - name: copy /etc/sysctl.conf - centos6 -
      copy:
        src: sysctl.conf
        dest: /etc/sysctl.conf
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

    - name: copy /etc/sysctl.conf - centos7 -
      copy:
        src: sysctl.conf
        dest: /etc/sysctl.conf
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
